apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  description: A simple test service
  tags:
    - demo
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
